### ISSUE TITLE
Test Windows Version: Warnings - '$SEARCH_STRING' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by brentonford** [Attune-Automation/Automate-Windows-Installation-with-autounattend#4]
**Test Windows Version: Warnings**
Last Run:On 08-Oct-2023 15:46 +11:00, it took 6.014s
Exit status is null
Time	Severity
Log Line
15:46:28	Stderr	'$SEARCH_STRING' is not recognized as an internal or external command,
15:46:28	Stderr	operable program or batch file.
15:46:28	Stderr	| was unexpected at this time.
15:46:29	Error	Operation aborted, timeout reached

<img width="1187" alt="2023-10-08_16-09-01" src="https://github.com/Attune-Automation/Automate-Windows-Installation-with-autounattend/assets/23700957/77a5aa95-ff07-4df6-8dc4-7771789fac9d">

**Comment by h4xhor** [comment]
Fixed.
