### ISSUE TITLE
Confirm boot Configuration: Warnings - Missing '(' after 'if' in if statement.

### ISSUE THREAD

**Issue by brentonford** [Attune-Automation/Automate-Windows-Installation-with-autounattend#5]
**Confirm boot Configuration: Warnings**
Last Run:On 08-Oct-2023 15:46 +11:00, it took 7.443s
Exit status is 1
Time	Severity
Log Line
15:46:35	Stderr	At C:\Users\Administrator\AppData\Local\Temp\tmpF018.tmp.ps1:2 char:3
15:46:35	Stderr	+ if true
15:46:35	Stderr	+   ~
15:46:35	Stderr	Missing '(' after 'if' in if statement.
15:46:35	Stderr	+ CategoryInfo          : ParserError: (:) [], ParseException
15:46:35	Stderr	+ FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement

<img width="1171" alt="2023-10-08_16-08-22" src="https://github.com/Attune-Automation/Automate-Windows-Installation-with-autounattend/assets/23700957/699ffb56-eea9-4ac2-bf48-69cc99501235">

**Comment by jarrodchesney** [comment]
As per my message in slack on the 06-Sep-2023, the correct syntax for Attune true/false values in Powershell IF connections is

```
if (${{attuneVal}}) {
    Write-Host "true"
}
```

**Comment by h4xhor** [comment]
Fixed.
