### ISSUE TITLE
Step "Extract Windows boot.img on Windows Worker" Requires wsl Installed as Prerequisite

### ISSUE THREAD

**Issue by h4xhor** [Attune-Automation/Automate-Windows-Installation-with-autounattend#54]
The steps that uses Windows Subsystem for Linux as an example step "Extract Windows boot.img on Windows Worker" requires `wsl` Installed as Prerequisite.

![image](https://github.com/Attune-Automation/Automate-Windows-Installation-with-autounattend/assets/14309370/573d8d97-102b-46a3-8365-ba243930e126)

**Comment by jarrodchesney** [comment]
@h4xhor  We need to us WSL2 as in "Windows Subsystem for Linux 2" - I've not checked, but I bet this is a different command to wsl, because it seemed pretty separate when installing it in the windows features.
